import 'package:flutter/material.dart';
import 'package:intl/intl.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import '../models/financial_transaction.dart';
import '../utils/currency_formatter.dart';

class PdfReportService {
  static Future<void> generateFarmReport({
    required BuildContext context,
    required String farmName,
    required String ownerName,
    required int totalBirds,
    required int totalBatches,
    required int totalEggs,
    required double totalRevenue,
    required double totalExpenses,
    required double netProfit,
    required List<FinancialTransaction> transactions,
  }) async {
    final pdf = pw.Document();
    final date = DateFormat('d MMMM yyyy').format(DateTime.now());

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(40),
        header: (ctx) => pw.Column(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: [
            pw.Row(
              mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
              children: [
                pw.Text(
                  'Hatch2Revenue Farm Report',
                  style: pw.TextStyle(fontSize: 18, fontWeight: pw.FontWeight.bold),
                ),
                pw.Text(date, style: const pw.TextStyle(fontSize: 10)),
              ],
            ),
            if (farmName.isNotEmpty)
              pw.Text(farmName, style: pw.TextStyle(fontSize: 13, fontWeight: pw.FontWeight.bold)),
            if (ownerName.isNotEmpty)
              pw.Text('Owner: $ownerName', style: const pw.TextStyle(fontSize: 10)),
            pw.Divider(color: PdfColors.grey400),
            pw.SizedBox(height: 4),
          ],
        ),
        build: (ctx) => [
          pw.Text('Farm Summary', style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold)),
          pw.SizedBox(height: 8),
          pw.Table.fromTextArray(
            headers: ['Metric', 'Value'],
            headerStyle: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 11),
            cellStyle: const pw.TextStyle(fontSize: 10),
            headerDecoration: const pw.BoxDecoration(color: PdfColors.grey200),
            border: pw.TableBorder.all(color: PdfColors.grey300, width: 0.5),
            data: [
              ['Total Birds', '$totalBirds'],
              ['Active Batches', '$totalBatches'],
              ['Total Eggs Produced', '$totalEggs'],
            ],
          ),
          pw.SizedBox(height: 16),
          pw.Text('Financial Summary', style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold)),
          pw.SizedBox(height: 8),
          pw.Table.fromTextArray(
            headers: ['Item', 'Amount'],
            headerStyle: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 11),
            cellStyle: const pw.TextStyle(fontSize: 10),
            headerDecoration: const pw.BoxDecoration(color: PdfColors.grey200),
            border: pw.TableBorder.all(color: PdfColors.grey300, width: 0.5),
            data: [
              ['Total Income', '${CurrencyFormatter.currencySymbol}${totalRevenue.toStringAsFixed(2)}'],
              ['Total Expenses', '${CurrencyFormatter.currencySymbol}${totalExpenses.toStringAsFixed(2)}'],
              ['Net Profit / (Loss)', '${CurrencyFormatter.currencySymbol}${netProfit.toStringAsFixed(2)}'],
            ],
          ),
          pw.SizedBox(height: 16),
          if (transactions.isNotEmpty) ...[
            pw.Text('Transaction History', style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold)),
            pw.SizedBox(height: 8),
            pw.Table.fromTextArray(
              headers: ['Date', 'Type', 'Category', 'Amount', 'Description'],
              headerStyle: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 9),
              cellStyle: const pw.TextStyle(fontSize: 9),
              headerDecoration: const pw.BoxDecoration(color: PdfColors.grey200),
              border: pw.TableBorder.all(color: PdfColors.grey300, width: 0.5),
              data: transactions.map((t) => [
                DateFormat('d/M/yy').format(t.date),
                t.type == TransactionType.income ? 'Income' : 'Expense',
                t.categoryName,
                '${t.type == TransactionType.income ? '+' : '-'}${CurrencyFormatter.currencySymbol}${t.amount.toStringAsFixed(2)}',
                t.description ?? '',
              ]).toList(),
            ),
          ],
          pw.SizedBox(height: 20),
          pw.Center(
            child: pw.Text(
              'Generated by Hatch2Revenue • $date',
              style: const pw.TextStyle(color: PdfColors.grey500, fontSize: 9),
            ),
          ),
        ],
      ),
    );

    await Printing.layoutPdf(
      onLayout: (PdfPageFormat format) async => pdf.save(),
      name: 'FarmReport_${DateFormat('yyyyMMdd').format(DateTime.now())}.pdf',
    );
  }

  // Legacy stub kept for compatibility
  static Future<void> generateFinancialReport({
    required List<dynamic> transactions,
    required double totalIncome,
    required double totalExpenses,
    required double netProfit,
  }) async {
    debugPrint('Use generateFarmReport() instead');
  }

  static Future<void> generateSummaryReport({
    required int totalBirds,
    required int totalBatches,
    required int totalCrates,
    required double totalRevenue,
    required double totalExpenses,
    required double netProfit,
  }) async {
    debugPrint('Use generateFarmReport() instead');
  }
}
