// One-off: renders the redesigned report header (farm name headline,
// app brand in footer) with sample profile data for visual verification.
// Output: build/header_test.pdf   Run: dart run tool/make_header_test_pdf.dart
import 'dart:io';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

Future<void> main() async {
  pw.Font ttf(String p) =>
      pw.Font.ttf(File(p).readAsBytesSync().buffer.asByteData());
  final theme = pw.ThemeData.withFont(
    base: ttf('google_fonts/Inter-Regular.ttf'),
    bold: ttf('google_fonts/Inter-Bold.ttf'),
  );

  const farmName = 'Nyarko Poultry Farm';
  const ownerName = 'Bright Nyarko';

  final pdf = pw.Document();
  pdf.addPage(pw.MultiPage(
    theme: theme,
    pageFormat: PdfPageFormat.a4,
    margin: const pw.EdgeInsets.all(40),
    header: (ctx) => pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Row(
          mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
          children: [
            pw.Text(farmName,
                style:
                    pw.TextStyle(fontSize: 18, fontWeight: pw.FontWeight.bold)),
            pw.Text('19 July 2026', style: const pw.TextStyle(fontSize: 10)),
          ],
        ),
        pw.Text('Farm Report',
            style: const pw.TextStyle(fontSize: 12, color: PdfColors.grey700)),
        pw.Text('Owner: $ownerName', style: const pw.TextStyle(fontSize: 10)),
        pw.Divider(color: PdfColors.grey400),
        pw.SizedBox(height: 4),
      ],
    ),
    footer: (ctx) => pw.Container(
      alignment: pw.Alignment.centerRight,
      margin: const pw.EdgeInsets.only(top: 8),
      child: pw.Text('Generated by Hatch2Revenue',
          style: const pw.TextStyle(fontSize: 8, color: PdfColors.grey600)),
    ),
    build: (ctx) => [
      pw.Text('Financial Summary',
          style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold)),
      pw.SizedBox(height: 8),
      pw.Text('Total Income: ₵12,345.00'),
      pw.Text('Net Profit / (Loss): ₵3,584.50'),
    ],
  ));
  File('build/header_test.pdf').writeAsBytesSync(await pdf.save());
  stdout.writeln('wrote build/header_test.pdf');
}
